version: '3.9'

services:

    db:
        image: postgres
        container_name: moex-postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: moex
            POSTGRES_USER: moex
            POSTGRES_DB: moex
        volumes:
            - ~/projects_data/moex:/var/lib/postgresql/data
        ports:
            - 5432:5432


    moex:
        image: moex:v0.2.0
        ports: 
            - 8080:8080
        container_name: moex
        restart: always
        links:
            - db


    migration:
        image: migrate/migrate:v4.14.1
        container_name: moex-migrate
        volumes:
            - ./migrations:/migrations
        command: ["-path", "/migrations", "-database",  "postgres://moex:moex@db:5432/moex?sslmode=disable", "up"]
        restart: on-failure
        links:
            - db